### PR TITLE
Make YAML handler safe by default

### LINKED ISSUE #43: Load and Dump safely by default
As I see it, safe behaviour should be default. PyYAML got that wrong. It would be nice if kaptan doesn't make the same mistake.

### PR DESCRIPTION
**Pull request by pradyunsg**
Fixes #43

### CODE REVIEW

**Comment by tony** [comment]
@pradyunsg Can you take a look at the tests?

**Comment by pradyunsg** [comment]
Yep. Will do.

**Comment by tony** [comment]
@pradyunsg  Any update on the test results at @ https://travis-ci.org/emre/kaptan/builds/219762219?

We can drop python 3.2 support, so that is ok.

**Comment by pradyunsg** [comment]
I'm kinda stuck with 0 time on GitHub to do any OSS work.

I think it's +2 -2 patch to fix the tests. If someone else could look at,
them, it'd be nice. 🙈

**Comment by pradyunsg** [comment]
@tony I think we're good. Please review and merge if it's fine.

PS: Those build times feel so good.

**Comment by tony** [comment]
LGTM 👍

**Comment by tony** [comment]
Would you like me to add you to the AUTHORS @pradyunsg ?

**Comment by pradyunsg** [comment]
Sure. Please do. ^.^

**Comment by tony** [comment]
@pradyunsg done

**Comment by tony** [comment]
@pradyunsg this is live in v0.5.9

**Comment by pradyunsg** [comment]
Awesome! 🎉

**Pull request merged**
